"""
AC-NF01 through AC-NF05: non-functional criteria.

Covers determinism, performance, stdlib-only imports, always-valid JSON output,
and stdin/file-path equivalence.
"""
import ast
import hashlib
import json
import subprocess
import sys
import time

import pytest

from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))  # ensure local conftest is found
from parser_helpers import load, parse, SAMPLES_DIR, PARSER_PATH

# (filename, family) — all fixtures across both address families
ALL_FIXTURES = [
    ("ubuntu2404-clean.txt",                      "ipv4"),
    ("ubuntu2404-clean-counters.txt",              "ipv4"),
    ("ubuntu2404-docker.txt",                      "ipv4"),
    ("ubuntu2404-docker-counters.txt",             "ipv4"),
    ("ubuntu2404-docker-fail2ban.txt",             "ipv4"),
    ("ubuntu2404-docker-fail2ban-wireguard.txt",   "ipv4"),
    ("ubuntu2404-cis-hardened.txt",                "ipv4"),
    ("ubuntu2404-log-mark-snat.txt",               "ipv4"),
    ("ubuntu2404-clean-ip6.txt",                   "ipv6"),
    ("ubuntu2404-docker-ip6.txt",                  "ipv6"),
    ("ubuntu2404-docker-ip6-counters.txt",         "ipv6"),
]


def test_nf01_determinism():
    """AC-NF01: Parsing any fixture file 10 times produces byte-identical JSON (excluding parsed_at)."""
    def stable_hash(d: dict) -> str:
        d2 = dict(d)
        d2.pop("parsed_at")
        return hashlib.md5(json.dumps(d2, sort_keys=True).encode()).hexdigest()

    for filename, family in ALL_FIXTURES:
        text = (SAMPLES_DIR / filename).read_text(encoding="utf-8")
        hashes = {stable_hash(parse(text, family=family)) for _ in range(10)}
        assert len(hashes) == 1, f"{filename} produces non-deterministic output"


@pytest.mark.slow
def test_nf02_performance():
    """AC-NF02 (SHOULD): All 11 fixture files parsed sequentially in under 2 seconds."""
    pairs = [
        ((SAMPLES_DIR / f).read_text(encoding="utf-8"), fam)
        for f, fam in ALL_FIXTURES
    ]

    start = time.perf_counter()
    for text, family in pairs:
        parse(text, family=family)
    elapsed = time.perf_counter() - start

    assert elapsed < 2.0, f"Parsing all {len(ALL_FIXTURES)} fixtures took {elapsed:.3f}s (limit: 2.0s)"


def test_nf03_no_external_dependencies():
    """AC-NF03: iptables_parser.py has no external (pip-installable) dependencies.

    stdlib modules and sibling modules in the iptables-parser package are permitted.
    The explain feature adds deferred imports of iptables_explain and iptables_diff
    inside the CLI path only — these are package-local siblings, not pip packages,
    and do not introduce external dependencies for library consumers.
    """
    known_stdlib = {
        "__future__", "sys", "json", "argparse", "re", "datetime", "typing",
        "os", "pathlib", "collections", "itertools", "functools", "io",
        "hashlib", "copy", "math", "string", "enum", "dataclasses",
    }
    # Sibling modules in the iptables-parser package — not pip packages.
    # Imported only inside CLI code paths; library consumers (import iptables_parser)
    # are not affected.
    known_siblings = {"iptables_explain", "iptables_diff"}

    source = PARSER_PATH.read_text(encoding="utf-8")
    tree = ast.parse(source)

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                top = alias.name.split(".")[0]
                assert top in known_stdlib | known_siblings, (
                    f"Non-stdlib import found: '{alias.name}' — "
                    "parser must use only standard library or sibling package modules"
                )
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                top = node.module.split(".")[0]
                assert top in known_stdlib | known_siblings, (
                    f"Non-stdlib import found: 'from {node.module} import ...' — "
                    "parser must use only standard library or sibling package modules"
                )


def test_nf04_output_is_always_valid_json():
    """AC-NF04: json.loads() succeeds for all input types; parse_warnings is always a list."""
    inputs = [
        # Completely empty
        "",
        # Comments only
        "# Generated by iptables-save\n",
        # Missing COMMIT
        "*filter\n:INPUT DROP [0:0]\n-A INPUT -j ACCEPT\n",
        # Invalid chain policy
        "*filter\n:INPUT REJECT [0:0]\nCOMMIT\n",
        # Unknown target
        "*filter\n:INPUT DROP [0:0]\nCOMMIT\n-A INPUT -j UNKNOWN\n",
        # Rule without -j
        "*filter\n:INPUT DROP [0:0]\n:FORWARD DROP [0:0]\n:OUTPUT ACCEPT [0:0]\n-A INPUT -p tcp\nCOMMIT\n",
    ]

    for text in inputs:
        result = parse(text)
        # Must always produce a dict with required top-level keys
        assert isinstance(result, dict)
        assert "tables" in result
        assert "parse_warnings" in result
        assert "diagnostics" in result
        assert "family" in result
        assert isinstance(result["parse_warnings"], list)

        # Serialise and deserialise — must not raise; all fields survive the round-trip
        serialised = json.dumps(result)
        deserialised = json.loads(serialised)
        assert deserialised["parse_warnings"] == result["parse_warnings"]
        assert deserialised["tables"] == result["tables"]
        assert deserialised["input_format"] == result["input_format"]
        assert deserialised["family"] == result["family"]
        assert "diagnostics" in deserialised


def test_nf05_stdin_and_file_path_produce_identical_output():
    """AC-NF05: CLI invoked with a file path and with stdin both produce identical output."""
    fixture_path = SAMPLES_DIR / "ubuntu2404-cis-hardened.txt"
    text = fixture_path.read_text(encoding="utf-8")

    # Via file path argument
    result_file = subprocess.run(
        [sys.executable, str(PARSER_PATH), str(fixture_path)],
        capture_output=True,
        text=True,
        check=True,
    )

    # Via stdin
    result_stdin = subprocess.run(
        [sys.executable, str(PARSER_PATH)],
        input=text,
        capture_output=True,
        text=True,
        check=True,
    )

    d_file = json.loads(result_file.stdout)
    d_stdin = json.loads(result_stdin.stdout)

    # Both must parse successfully
    assert d_file["tables"] == d_stdin["tables"]
    assert d_file["parse_warnings"] == d_stdin["parse_warnings"]
    assert d_file["diagnostics"] == d_stdin["diagnostics"]
    assert d_file["input_format"] == d_stdin["input_format"]
    assert d_file["family"] == d_stdin["family"]
    # parsed_at may differ; all other fields must be identical
